### ISSUE TITLE
Incompatible with iputils ping

### ISSUE THREAD

**Issue by Yepoleb** [frdmn/uping#2]
The -t parameter is used for setting the TTL in iputils ping and a value of 1 makes all WAN pings fail. Using -W should work on all platforms and provide the same effect.

**Comment by frdmn** [comment]
Thanks for reporting! :)

**Comment by Yepoleb** [comment]
8845897a9f5604809fe3e89a5324d009a0a9288d only replaces one `-t`, there's another one at line 25.
